import { Fragment } from "react";

import { DeskExperience } from "@/components/desk/desk-experience";
import type { DeskHotspotData } from "@/lib/desk/hotspots";
import {
  deskSceneMarkup,
  deskSceneStrokeWidth,
  deskSceneViewBox,
} from "@/lib/desk/scene-markup";

/**
 * Inlines the generated scene as real SVG.
 *
 * This is a Server Component on purpose: its code never reaches the browser, so
 * the markup ships once inside the HTML rather than as a string in the client
 * bundle. Inlining is what makes each object a hoverable element — an `<img>`
 * can only ever be hovered as a whole rectangle.
 *
 * The markup is generated by `scripts/generate-desk.ts` from typed scene data
 * and is covered by the passive-SVG test, which bans scripts, event handlers,
 * remote references, and `<foreignObject>`.
 */
export function IsometricDesk({
  hotspots,
}: Readonly<{ hotspots: readonly DeskHotspotData[] }>) {
  return (
    <DeskExperience
      hotspots={hotspots}
      scene={
        // Carried as a prop into a multi-child position in `DeskExperience`, so
        // React validates it as a list item and wants a key even though there is
        // only ever one of it. That is also why this is `Fragment` written out
        // rather than `<>`, which cannot take one.
        <Fragment key="desk-scene">
          {/*
           * The artwork spells "Walk through my workbench!" out of cubes, and
           * the SVG below is `aria-hidden`, so without this the invitation
           * reaches nobody using a screen reader. It is also the only form of
           * the phrase that survives a phone: the field renders at about a
           * quarter scale there, where a cube is under three pixels.
           *
           * If the lettering ever leaves the scene, this goes with it.
           */}
          <p className="sr-only">Walk through my workbench.</p>
          <svg
            aria-hidden="true"
            className="desk-art"
            fill="none"
            preserveAspectRatio="xMidYMid meet"
            strokeWidth={deskSceneStrokeWidth}
            viewBox={deskSceneViewBox}
            dangerouslySetInnerHTML={{ __html: deskSceneMarkup }}
          />
        </Fragment>
      }
    />
  );
}
