import { DeskExperience } from "@/components/desk/desk-experience";
import type { DeskHotspotData } from "@/lib/desk/hotspots";
import {
  deskSceneMarkup,
  deskSceneStrokeWidth,
  deskSceneViewBox,
} from "@/lib/desk/scene-markup";

/**
 * Inlines the generated scene as real SVG.
 *
 * This is a Server Component on purpose: its code never reaches the browser, so
 * the markup ships once inside the HTML rather than as a string in the client
 * bundle. Inlining is what makes each object a hoverable element — an `<img>`
 * can only ever be hovered as a whole rectangle.
 *
 * The markup is generated by `scripts/generate-desk.ts` from typed scene data
 * and is covered by the passive-SVG test, which bans scripts, event handlers,
 * remote references, and `<foreignObject>`.
 */
export function IsometricDesk({
  hotspots,
}: Readonly<{ hotspots: readonly DeskHotspotData[] }>) {
  return (
    <DeskExperience
      hotspots={hotspots}
      scene={
        <svg
          aria-hidden="true"
          className="desk-art"
          fill="none"
          preserveAspectRatio="xMidYMid meet"
          strokeWidth={deskSceneStrokeWidth}
          viewBox={deskSceneViewBox}
          dangerouslySetInnerHTML={{ __html: deskSceneMarkup }}
        />
      }
    />
  );
}
