// Generated by scripts/generate-desk.ts. Do not edit by hand.
// Hotspot bounds and screen corners are derived from the artwork, so the
// overlay geometry cannot drift away from the illustration.

export const deskSceneGeometry = {
  viewBox: { x: -69.2, y: -160.62, width: 271.27, height: 271.27 },
  aspectRatio: 1,
  monitorScreen: [
    { xPercent: 41.55, yPercent: 34.14 },
    { xPercent: 64.03, yPercent: 42.68 },
    { xPercent: 64.03, yPercent: 54.85 },
    { xPercent: 41.55, yPercent: 46.3 },
  ],
  monitorScreenBounds: { xPercent: 41.55, yPercent: 34.14, widthPercent: 22.48, heightPercent: 20.71 },
  hotspots: {
    "leadership": { tier: "hero", xPercent: 20.57, yPercent: 29.51, widthPercent: 12.68, heightPercent: 16.639999999999997 },
    "maker": { tier: "hero", xPercent: 31.4, yPercent: 33.43, widthPercent: 12.170000000000002, heightPercent: 16.740000000000002 },
    "food-favorites": { tier: "hero", xPercent: 69.28, yPercent: 48, widthPercent: 12.629999999999995, heightPercent: 16.28 },
    "shared-food": { tier: "hero", xPercent: 80.92, yPercent: 51.92, widthPercent: 11.310000000000002, heightPercent: 16.36 },
    "climbing": { tier: "detail", xPercent: 22.65, yPercent: 15.5, widthPercent: 10.600000000000001, heightPercent: 16.33 },
    "gym": { tier: "detail", xPercent: 32.37, yPercent: 19.42, widthPercent: 11.200000000000003, heightPercent: 16.509999999999998 },
    "anime": { tier: "detail", xPercent: 70.72, yPercent: 33.99, widthPercent: 11.189999999999998, heightPercent: 16.759999999999998 },
    "quackta": { tier: "detail", xPercent: 80.22, yPercent: 37.91, widthPercent: 12.010000000000005, heightPercent: 16.540000000000006 },
  },
} as const;
