// Generated by scripts/generate-desk.ts. Do not edit by hand.
// Hotspot bounds are derived from the artwork, so the overlay geometry
// cannot drift away from the illustration.

export const deskSceneGeometry = {
  viewBox: { x: -193.96, y: -38.5, width: 491.92, height: 245.28 },
  aspectRatio: 2.0056,
  hotspots: {
    "maker": { tier: "hero", xPercent: 29.79, yPercent: 28.27, widthPercent: 9.130000000000003, heightPercent: 9.73 },
    "colophon": { tier: "detail", xPercent: 56.51, yPercent: 20.18, widthPercent: 10.160000000000004, heightPercent: 23.130000000000003 },
    "anime": { tier: "detail", xPercent: 20.93, yPercent: 30.17, widthPercent: 4.879999999999999, heightPercent: 10.600000000000001 },
    "quackta": { tier: "hero", xPercent: 42.68, yPercent: 39.45, widthPercent: 6.240000000000002, heightPercent: 12.629999999999995 },
    "shared-food": { tier: "hero", xPercent: 70.71, yPercent: 41.99, widthPercent: 8.300000000000011, heightPercent: 13.369999999999997 },
    "taekwondo": { tier: "detail", xPercent: 18.57, yPercent: 49.93, widthPercent: 7.23, heightPercent: 12.899999999999999 },
    "scouting": { tier: "detail", xPercent: 32.08, yPercent: 55.4, widthPercent: 5.75, heightPercent: 7.6200000000000045 },
    "music": { tier: "detail", xPercent: 48.06, yPercent: 59.25, widthPercent: 7.75, heightPercent: 11.010000000000005 },
    "climbing": { tier: "detail", xPercent: 62.93, yPercent: 53.61, widthPercent: 3.1300000000000026, heightPercent: 15.370000000000005 },
    "kirby": { tier: "detail", xPercent: 37.97, yPercent: 60.95, widthPercent: 6.200000000000003, heightPercent: 9.719999999999999 },
    "gym": { tier: "detail", xPercent: 72.78, yPercent: 62.46, widthPercent: 8.120000000000005, heightPercent: 11.660000000000004 },
    "food-favorites": { tier: "detail", xPercent: 55.35, yPercent: 72.31, widthPercent: 5.509999999999998, heightPercent: 6.640000000000001 },
    "triforce": { tier: "detail", xPercent: 46.75, yPercent: 70.63, widthPercent: 5.159999999999997, heightPercent: 10.710000000000008 },
  },
} as const;
