// Generated by scripts/generate-desk.ts. Do not edit by hand.
// Hotspot bounds are derived from the artwork, so the overlay geometry
// cannot drift away from the illustration.

export const deskSceneGeometry = {
  viewBox: { x: -195.52, y: -38.5, width: 495.04, height: 246.83 },
  aspectRatio: 2.0056,
  hotspots: {
    "maker": { tier: "hero", xPercent: 31.11, yPercent: 27.25, widthPercent: 9.079999999999998, heightPercent: 10.920000000000002 },
    "colophon": { tier: "detail", xPercent: 56.46, yPercent: 20.05, widthPercent: 10.100000000000001, heightPercent: 22.98 },
    "anime": { tier: "detail", xPercent: 19.09, yPercent: 28.72, widthPercent: 9.030000000000001, heightPercent: 15 },
    "quackta": { tier: "hero", xPercent: 41.92, yPercent: 33.83, widthPercent: 8.280000000000001, heightPercent: 15.25 },
    "taekwondo": { tier: "detail", xPercent: 27.24, yPercent: 45.03, widthPercent: 5.120000000000001, heightPercent: 5.6299999999999955 },
    "shared-food": { tier: "hero", xPercent: 71.26, yPercent: 42.54, widthPercent: 6.5, heightPercent: 13.730000000000004 },
    "scouting": { tier: "detail", xPercent: 32.92, yPercent: 55.59, widthPercent: 4.269999999999996, heightPercent: 4.349999999999994 },
    "climbing": { tier: "detail", xPercent: 63.13, yPercent: 51.25, widthPercent: 5.050000000000004, heightPercent: 15.599999999999994 },
    "gym": { tier: "detail", xPercent: 73.84, yPercent: 65.43, widthPercent: 5.6499999999999915, heightPercent: 7.709999999999994 },
    "food-favorites": { tier: "detail", xPercent: 55.31, yPercent: 71.3, widthPercent: 5.469999999999999, heightPercent: 7.150000000000006 },
  },
} as const;
