import type { Project } from "@/types/content";

export const projects = [
  {
    slug: "cisco-agentic-runbook-creator",
    title: "Cisco - Agentic Runbook Creator",
    category: "AI Systems",
    shortDescription:
      "At Cisco, I worked on Agentic Runbook Creator, an industrial-network troubleshooting system that combined local model reasoning, privacy-aware cloud handoffs, and digital-twin evaluation to generate and test runbooks.",
    role: "Software Engineer Intern",
    startDate: "2026-05",
    endDate: "2026-08",
    technologies: [
      "Python",
      "Flask",
      "Small Language Models",
      "Large Language Models",
      "MCP Tools",
      "Network Simulation",
      "Digital Twins",
      "Cisco IOS XE",
    ],
    workMode: "software",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 10,
    links: [],
    metrics: [
      {
        label: "Previous procedure set",
        value: "13",
        context: "The project expanded troubleshooting beyond a fixed catalog of predefined procedures.",
      },
      {
        label: "Triage time",
        value: "<25 min",
        context: "Reduced from hours to under 25 minutes.",
      },
    ],
    videos: [],
    assets: [
      {
        kind: "hero",
        path: "/media/projects/cisco-agentic-runbook-creator/me-in-front-of-cisco-sign.webp",
        alt: "Lakshya standing beside a large white Cisco sign on a blue lobby wall",
        caption: "In front of the Cisco sign.",
        width: 1170,
        height: 640,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/cisco-agentic-runbook-creator/intern-cohort-at-final-presentations.webp",
        alt: "Interns seated at long tables in a Cisco conference room with laptops, balloons, and remote attendees on a video wall behind them",
        caption: "The intern cohort at final presentations.",
        width: 1800,
        height: 1219,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/cisco-agentic-runbook-creator/interns-watch-the-odyssey-in-theaters.webp",
        alt: "Six interns along a row of recliners in a cinema, holding popcorn and drinks",
        caption: "The cohort went to see The Odyssey.",
        width: 1800,
        height: 1350,
        placeholder: false,
      },
    ],
  },
  {
    slug: "repoframe",
    title: "RepoFrame",
    category: "Developer Tools",
    shortDescription:
      "I built RepoFrame to turn bounded repository evidence into defensible project stories, with deterministic inspection and tool-using verification keeping generated claims traceable.",
    role: "Creator and full-stack engineer",
    startDate: "2026-06",
    endDate: "present",
    technologies: [
      "Next.js",
      "TypeScript",
      "FastAPI",
      "Python",
      "Supabase",
      "GitHub API",
      "OpenAI",
    ],
    workMode: "software",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 20,
    links: [
      {
        kind: "repository",
        label: "View the source repository",
        href: "https://github.com/Lakshya565/RepoFrame",
      },
    ],
    metrics: [
      {
        label: "Evidence policy",
        value: "Bounded",
        context: "Retrieval is limited to allowlisted repository evidence.",
      },
      {
        label: "Core written outputs",
        value: "4",
        context: "Resume, README, portfolio, and LinkedIn content.",
      },
    ],
    videos: [],
    assets: [
      {
        kind: "hero",
        path: "/media/projects/repoframe/working-on-repoframe-at-breaktime-tea.webp",
        alt: "A laptop open to the RepoFrame repository in a code editor on a cafe table, beside a boba tea and a box of popcorn chicken",
        caption: "Building RepoFrame at BreakTime Tea.",
        width: 1012,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/repoframe/snapshot-of-custom-isometric-bench.webp",
        alt: "An isometric line-art workbench on a dark grid, carrying a monitor, an Arduino and breadboard, headphones, boba cups and a dumbbell, under the heading Walk through my workbench",
        caption: "The isometric workbench I drew and vectorised for this portfolio.",
        width: 1800,
        height: 862,
        placeholder: false,
      },
    ],
  },
  {
    slug: "nucurrent-inventory-system",
    title: "NuCurrent Inventory Platform",
    category: "Full-stack Software",
    shortDescription:
      "As CUBE Consulting's frontend lead, I helped replace spreadsheet-based part tracking with a React, FastAPI, and SQL inventory platform built around daily maintenance work.",
    role: "Technical consultant and frontend lead",
    startDate: "2026-01",
    endDate: "2026-05",
    technologies: ["React", "FastAPI", "SQL", "REST APIs", "Barcode Scanning"],
    workMode: "software",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 30,
    links: [
      {
        kind: "live",
        label: "Visit NuCurrent",
        href: "https://www.nucurrent.com/",
      },
      {
        kind: "live",
        label: "About CUBE Consulting",
        href: "https://www.cubeconsulting.org/",
      },
    ],
    metrics: [
      {
        label: "Frontend workflows",
        value: "4",
        context: "Part search, check-in and check-out, barcode scanning, and label generation.",
      },
      {
        label: "Replaced",
        value: "Spreadsheets",
        context: "Distributed part data and stock changes became one consistent source.",
      },
    ],
    videos: [],
    assets: [
      {
        kind: "hero",
        path: "/media/projects/nucurrent-inventory-system/professional-photo-of-the-consultant-team.webp",
        alt: "Seven consultants in suits standing on the steps of a columned brick campus building",
        caption:
          "The CUBE Consulting team. The platform itself is an internal tool, so there are no product screenshots here.",
        width: 1200,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/nucurrent-inventory-system/funny-photo-of-the-consultant-team.webp",
        alt: "The same seven consultants on the same steps, mid-jump with their arms flung out",
        caption: "The same team, one frame later.",
        width: 1800,
        height: 1200,
        placeholder: false,
      },
    ],
  },
  {
    slug: "smartlift-sleeve",
    title: "SmartLift Sleeve",
    category: "Hardware",
    shortDescription:
      "On a three-person team, I led the hardware logic that turned flex and pulse signals into live rep counts and exertion feedback without firmware.",
    role: "Project lead and hardware engineer",
    startDate: "2026-01",
    endDate: "2026-05",
    technologies: [
      "Analog Signal Conditioning",
      "Digital Logic",
      "PCB Design",
      "Sensors",
      "Seven-Segment Displays",
    ],
    workMode: "hardware",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 40,
    links: [
      {
        kind: "live",
        label: "Read the final report",
        href: "https://docs.google.com/document/d/1cCzJ8lISLLhE4yzjLJxJp5p-JJJQ-S5TbfhIbs_qMEc/edit?usp=sharing",
      },
    ],
    metrics: [
      {
        label: "Team size",
        value: "3",
        context: "An ECE 145 project at UIUC.",
      },
      {
        label: "Implementation",
        value: "No firmware",
        context: "Hardware logic only: no app, smartwatch, or microcontroller in the loop.",
      },
    ],
    videos: [
      {
        label: "Watch the project demo",
        href: "https://youtu.be/zs9B30EeIYc?t=309",
        thumbnailPath: "/media/projects/smartlift-sleeve/video-smartlift-sleeve.webp",
      },
    ],
    assets: [
      {
        kind: "hero",
        path: "/media/projects/smartlift-sleeve/final-circuit.webp",
        alt: "Three breadboards wired together with logic chips, a blue seven-segment display, an LED bar graph and rows of red, amber and green LEDs, fed from a lab power supply",
        caption: "The final circuit.",
        width: 1350,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/smartlift-sleeve/the-team.webp",
        alt: "Three teammates seated at a university electronics bench, with oscilloscopes and supplies racked behind them and the breadboard build on the bench",
        caption: "The team at the bench.",
        width: 1800,
        height: 1350,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/smartlift-sleeve/working-on-the-final-video.webp",
        alt: "A teammate cutting the project video in an editor on a laptop, seen over the shoulder",
        caption: "Cutting the final video.",
        width: 1013,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/smartlift-sleeve/video-smartlift-sleeve.webp",
        alt: "Title card for the SmartLift Sleeve demo video",
        width: 480,
        height: 270,
        placeholder: false,
      },
    ],
  },
  {
    slug: "quackta",
    title: "QuackTA",
    category: "Embedded Systems",
    shortDescription:
      "On a five-person hackathon team, I worked across hardware, AI, and integration to turn rubber-duck debugging into a physical ECE teaching assistant.",
    role: "Hardware, AI, and integration team member",
    startDate: "2026-03",
    endDate: "2026-03",
    technologies: [
      "Raspberry Pi 5",
      "Arduino Uno R4 Minima",
      "GPT-4o mini",
      "3D Printing",
      "App UI",
    ],
    workMode: "hybrid",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 50,
    links: [],
    metrics: [
      {
        label: "Team size",
        value: "5",
        context: "Built during UIUC IEEE's Bit-by-Bit Hardware Hackathon, March 28 to 29, 2026.",
      },
      {
        label: "Tutoring model",
        value: "GPT-4o mini",
        context: "Given UIUC ECE course and schedule context, and harnessed to guide rather than answer.",
      },
    ],
    videos: [],
    assets: [
      {
        kind: "hero",
        path: "/media/projects/quackta/final-quackta-model.webp",
        alt: "A bright green 3D-printed duck with ribbon cable running out of its base, standing on a white cardboard plinth in a classroom",
        caption: "The finished QuackTA model.",
        width: 1350,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/quackta/the-ieee-hackathon-team.webp",
        alt: "Five teammates holding the green duck together in a lecture room, with a Grainger College of Engineering slide projected behind them",
        caption: "The team at IEEE's Bit-by-Bit hackathon.",
        width: 1800,
        height: 1350,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/quackta/our-workbench-after-a-night-in-eceb.webp",
        alt: "A table strewn with jumper wires, an Arduino, a Raspberry Pi, a motor, a breadboard and two laptops running code",
        caption: "Our workbench after a night in ECEB.",
        width: 1350,
        height: 1800,
        placeholder: false,
      },
    ],
  },
  {
    slug: "lucky-arduino",
    title: "Lucky Arduino",
    category: "Embedded Systems",
    shortDescription:
      "I taught myself electronics in public through more than fifty Arduino videos, twelve documented builds, and repositories spanning sensors, displays, controls, and electromechanical systems.",
    role: "Creator and embedded-systems educator",
    startDate: "2023-11",
    endDate: "2025-08",
    technologies: [
      "Arduino",
      "C/C++",
      "Sensors",
      "Servos",
      "Displays",
      "IR Control",
      "Serial Communication",
      "HTML/CSS",
    ],
    workMode: "hybrid",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 100,
    links: [
      {
        kind: "repository",
        label: "Basic electronics repository",
        href: "https://github.com/Lakshya565/Basic-Electronics-Projects",
      },
      {
        kind: "repository",
        label: "Advanced electronics repository",
        href: "https://github.com/Lakshya565/Substantial-Electronics-Projects",
      },
      {
        kind: "live",
        label: "Visit Lucky Arduino",
        href: "https://luckyarduino.weebly.com",
      },
      {
        kind: "video",
        label: "Watch on YouTube",
        href: "https://www.youtube.com/@LuckyArduino",
      },
    ],
    metrics: [
      {
        label: "Video views",
        value: "50K+",
        context: "Across the Lucky Arduino channel.",
      },
      {
        label: "Documented builds",
        value: "12",
        context: "Six introductory and six substantial Arduino projects.",
      },
      {
        label: "Published videos",
        value: "50+",
        context: "Instructional and project-based Arduino videos.",
      },
      {
        label: "Subscribers",
        value: "200+",
        context: "On the Lucky Arduino channel.",
      },
    ],
    assets: [
      {
        kind: "hero",
        path: "/media/projects/lucky-arduino/led-tutorial-circuit.webp",
        alt: "An Arduino Uno wired across a breadboard to five coloured LEDs and their resistors, in front of an open laptop",
        caption: "The circuit from the LED tutorial.",
        width: 1800,
        height: 1350,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/lucky-arduino/rgb-led-circuit.webp",
        alt: "An Arduino Uno driving a single RGB LED on a small breadboard over three jumper wires",
        caption: "The RGB LED build.",
        width: 1170,
        height: 652,
        placeholder: false,
      },
      /* One title card per long-form video below. The channel is the project,
         so its catalog is the gallery. */
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-introduction-to-arduino.webp",
        alt: "Title card for the Introduction to Arduino video",
        width: 640,
        height: 360,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-wheel-of-fortune.webp",
        alt: "Title card for the Wheel of Fortune video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-christmas-song-player.webp",
        alt: "Title card for the Christmas Song Player video",
        width: 480,
        height: 270,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-variable-light-control.webp",
        alt: "Title card for the Variable Light Control video",
        width: 480,
        height: 270,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-night-light.webp",
        alt: "Title card for the Night Light video",
        width: 640,
        height: 360,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-light-show.webp",
        alt: "Title card for the Light Show video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-miniature-safe.webp",
        alt: "Title card for the Miniature Safe video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-stopwatch.webp",
        alt: "Title card for the Stopwatch video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-3d-printing.webp",
        alt: "Title card for the video on the processes behind 3D printing",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-simple-alarm.webp",
        alt: "Title card for the Simple Alarm video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-rgb-led-user-input.webp",
        alt: "Title card for the video on controlling an RGB LED with user input",
        width: 480,
        height: 270,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-multi-axis-robotics.webp",
        alt: "Title card for the Multi-Axis Robotics video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-calculator.webp",
        alt: "Title card for the Calculator video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-warning-system.webp",
        alt: "Title card for the Warning System video",
        width: 640,
        height: 360,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-dinosaur-game.webp",
        alt: "Title card for the video on playing the dinosaur game",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-automatic-fan.webp",
        alt: "Title card for the Automatic Fan video",
        width: 640,
        height: 360,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-alarm-system.webp",
        alt: "Title card for the Alarm System video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/lucky-arduino/video-distance-detector.webp",
        alt: "Title card for the Distance Detector video",
        width: 1280,
        height: 720,
        placeholder: false,
      },
    ],
    /* The long-form catalog, most-watched first after the introduction. The
       channel's Shorts are not listed here: there are thirty-odd of them and
       they are not walkthroughs. */
    videos: [
      {
        label: "Introduction to Arduino",
        href: "https://www.youtube.com/watch?v=Bpe7-Pu1JDo",
        thumbnailPath: "/media/projects/lucky-arduino/video-introduction-to-arduino.webp",
      },
      {
        label: "Wheel of Fortune",
        href: "https://www.youtube.com/watch?v=WOQkkcjZ2zU",
        thumbnailPath: "/media/projects/lucky-arduino/video-wheel-of-fortune.webp",
      },
      {
        label: "Christmas Song Player",
        href: "https://www.youtube.com/watch?v=twz3kWyBywc",
        thumbnailPath: "/media/projects/lucky-arduino/video-christmas-song-player.webp",
      },
      {
        label: "Variable Light Control",
        href: "https://www.youtube.com/watch?v=mCuvHNvAsZ4",
        thumbnailPath: "/media/projects/lucky-arduino/video-variable-light-control.webp",
      },
      {
        label: "Night Light",
        href: "https://www.youtube.com/watch?v=-7JsReFm2AI",
        thumbnailPath: "/media/projects/lucky-arduino/video-night-light.webp",
      },
      {
        label: "Light Show",
        href: "https://www.youtube.com/watch?v=LCdBfdS7Dy0",
        thumbnailPath: "/media/projects/lucky-arduino/video-light-show.webp",
      },
      {
        label: "Miniature Safe",
        href: "https://www.youtube.com/watch?v=VKlaSR3YDkI",
        thumbnailPath: "/media/projects/lucky-arduino/video-miniature-safe.webp",
      },
      {
        label: "Stopwatch",
        href: "https://www.youtube.com/watch?v=um56r5yoKdU",
        thumbnailPath: "/media/projects/lucky-arduino/video-stopwatch.webp",
      },
      {
        label: "The Processes Behind 3D Printing",
        href: "https://www.youtube.com/watch?v=H2PkhnuADSk",
        thumbnailPath: "/media/projects/lucky-arduino/video-3d-printing.webp",
      },
      {
        label: "Simple Alarm, with a twist",
        href: "https://www.youtube.com/watch?v=UnO6aPJ7824",
        thumbnailPath: "/media/projects/lucky-arduino/video-simple-alarm.webp",
      },
      {
        label: "Controlling an RGB LED with User Input",
        href: "https://www.youtube.com/watch?v=QZHzapXn7Y4",
        thumbnailPath: "/media/projects/lucky-arduino/video-rgb-led-user-input.webp",
      },
      {
        label: "Multi-Axis Robotics",
        href: "https://www.youtube.com/watch?v=n-9RNnsx_Kc",
        thumbnailPath: "/media/projects/lucky-arduino/video-multi-axis-robotics.webp",
      },
      {
        label: "Calculator",
        href: "https://www.youtube.com/watch?v=yBaDVT1eOXk",
        thumbnailPath: "/media/projects/lucky-arduino/video-calculator.webp",
      },
      {
        label: "Warning System",
        href: "https://www.youtube.com/watch?v=fh4u1xg80Yk",
        thumbnailPath: "/media/projects/lucky-arduino/video-warning-system.webp",
      },
      {
        label: "Playing the Dinosaur Game",
        href: "https://www.youtube.com/watch?v=mBBkEaCj_Fs",
        thumbnailPath: "/media/projects/lucky-arduino/video-dinosaur-game.webp",
      },
      {
        label: "Automatic Fan",
        href: "https://www.youtube.com/watch?v=EnEz-JWezNM",
        thumbnailPath: "/media/projects/lucky-arduino/video-automatic-fan.webp",
      },
      {
        label: "Alarm System",
        href: "https://www.youtube.com/watch?v=1QRMJM4se2o",
        thumbnailPath: "/media/projects/lucky-arduino/video-alarm-system.webp",
      },
      {
        label: "Distance Detector",
        href: "https://www.youtube.com/watch?v=K36bjE2wi0s",
        thumbnailPath: "/media/projects/lucky-arduino/video-distance-detector.webp",
      },
    ],
  },
  {
    slug: "backbuddy",
    title: "BackBuddy",
    category: "Hardware",
    shortDescription:
      "I designed and built an electronic posture brace whose custom circuit and PCB vibrated when the wearer hunched, earning second place among more than thirty capstones.",
    role: "Designer and builder",
    startDate: "2025-01",
    endDate: "2025-05",
    technologies: ["PCB Design", "Basic Circuitry", "Hardware Prototyping"],
    workMode: "hardware",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 110,
    links: [],
    metrics: [
      {
        label: "Capstone result",
        value: "2nd place",
        context: "Engineering and product pitch among more than 30 projects.",
      },
      {
        label: "Team size",
        value: "3",
        context: "Built for the PLTW Engineering Design and Development capstone.",
      },
    ],
    assets: [
      {
        kind: "hero",
        path: "/media/projects/backbuddy/circuit-prototype.webp",
        alt: "The posture brace laid flat with its circuit exposed: three vibration motors, a two-cell AA pack, a tilt switch and a rocker switch joined by soldered red and blue wire",
        caption: "The circuit prototype, before the components were covered.",
        width: 1350,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/backbuddy/the-team.webp",
        alt: "Three teammates standing with the brace held between them, in front of their presentation board",
        caption: "The team with the brace.",
        width: 1012,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/backbuddy/final-presentation-trifold.webp",
        alt: "The BackBuddy trifold board: problem statement, customer survey, competitor analysis, a Gantt chart, a hand-drawn circuit and the design process",
        caption: "The final presentation board.",
        width: 1800,
        height: 1370,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/backbuddy/video-backbuddy.webp",
        alt: "Title card for the BackBuddy video",
        width: 640,
        height: 360,
        placeholder: false,
      },
    ],
    videos: [
      {
        label: "Watch the BackBuddy build",
        href: "https://www.youtube.com/watch?v=g1s85o4gONg",
        thumbnailPath: "/media/projects/backbuddy/video-backbuddy.webp",
      },
    ],
  },
  {
    slug: "neurify",
    title: "Neurify",
    category: "AI Systems",
    shortDescription:
      "I contributed signal-processing and software work to an EEG headset that classified emotional state in Python and used the result to control Spotify playback.",
    role: "Signal-processing and software contributor",
    startDate: "2025-08",
    endDate: "2025-08",
    technologies: ["Python", "EEG", "Signal Processing", "Spotify"],
    workMode: "hybrid",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 120,
    links: [],
    metrics: [
      {
        label: "Response latency",
        value: "<100 ms",
        context: "Classification in real time rather than from preloaded data.",
      },
      {
        label: "Interfaces",
        value: "2",
        context: "A custom API alongside the Spotify Web API, covering deprecated functions.",
      },
    ],
    // No photographs were taken during this build.
    assets: [],
    videos: [],
  },
  {
    slug: "agrisense",
    title: "AgriSense",
    category: "Embedded Systems",
    shortDescription:
      "I built backend software and researched hardware for an IoT agriculture platform that connected environmental sensors, live visualization, and data-informed recommendations.",
    role: "Backend developer and hardware researcher",
    startDate: "2025-08",
    endDate: "2025-12",
    technologies: ["Python", "Flask", "IoT", "Sensors"],
    workMode: "hybrid",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 130,
    links: [
      {
        kind: "repository",
        label: "View the source repository",
        href: "https://github.com/Lakshya565/agri-sense",
      },
    ],
    metrics: [
      {
        label: "Sensor poll",
        value: "10 s",
        context: "An API automates collection on a ten-second trigger.",
      },
      {
        label: "Sensor types",
        value: "4",
        context: "Temperature, heat, soil quality, and moisture.",
      },
    ],
    // No photographs were taken during this build.
    assets: [],
    videos: [],
  },
  {
    slug: "risenrun-wifi-alarm-clock",
    title: "COSMOS RiseNRun",
    category: "Embedded Systems",
    shortDescription:
      "I developed embedded firmware and IoT behavior for a moving ESP32 alarm clock, then helped evaluate its adaptive physical tasks through deployment and user trials.",
    role: "Embedded firmware and IoT developer",
    startDate: "2024-07",
    endDate: "2024-08",
    technologies: ["C/C++", "ESP32", "MQTT", "Wi-Fi", "Motors", "Hardware Controls"],
    workMode: "hardware",
    publication: "published",
    contentStatus: "reviewed",
    displayOrder: 140,
    links: [
      {
        kind: "repository",
        label: "View the source repository",
        href: "https://github.com/Lakshya565/RiseNRun",
      },
    ],
    metrics: [
      {
        label: "Evaluation",
        value: "User trials",
        context: "Tested beyond the lab through real-world deployment and user trials.",
      },
      {
        label: "Team size",
        value: "2",
        context: "Developed with one partner through COSMOS.",
      },
    ],
    assets: [
      {
        kind: "hero",
        path: "/media/projects/risenrun-wifi-alarm-clock/risenrun-prototype.webp",
        alt: "The RiseNRun prototype on a tiled floor: a wheeled robot base carrying a control board, joystick, buttons and a whip antenna, with a 3D-printed hand and forearm lying beside it",
        caption: "The prototype, mid-build.",
        width: 1350,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/risenrun-wifi-alarm-clock/uc-davis-fab-cleanroom-trip.webp",
        alt: "About twenty people in white cleanroom suits and masks posed together inside a fabrication cleanroom, with a yellow lithography bay behind them",
        caption: "Inside the UC Davis fab cleanroom.",
        width: 1012,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "gallery",
        path: "/media/projects/risenrun-wifi-alarm-clock/me-and-my-friends.webp",
        alt: "Two COSMOS UC Davis photo booth strips on a wooden table, each showing three frames of a group in novelty glasses and leis",
        caption: "Photo booth strips from COSMOS.",
        width: 1350,
        height: 1800,
        placeholder: false,
      },
      {
        kind: "video-thumbnail",
        path: "/media/projects/risenrun-wifi-alarm-clock/video-risenrun.webp",
        alt: "Title card for the RiseNRun video",
        width: 640,
        height: 360,
        placeholder: false,
      },
    ],
    videos: [
      {
        label: "Watch the RiseNRun build",
        href: "https://www.youtube.com/watch?v=zqummEft2HI",
        thumbnailPath: "/media/projects/risenrun-wifi-alarm-clock/video-risenrun.webp",
      },
    ],
  },
] as const satisfies readonly Project[];
