import type { Project } from "@/types/content";

export const projects = [
  {
    slug: "cisco-agentic-runbook-creator",
    title: "Cisco Agentic Runbook Creator",
    category: "AI Systems",
    shortDescription:
      "An agentic troubleshooting system that assembles and evaluates dynamic industrial-network runbooks while respecting the boundary between on-premises and cloud processing.",
    role: "Software Engineering Intern",
    startDate: null,
    endDate: null,
    technologies: ["Python", "Flask", "Small Language Models", "Digital Twins"],
    accent: "green",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 10,
    displayInMap: true,
    presentation: "case-study",
    priority: "featured",
    caseStudyKey: "cisco-agentic-runbook-creator",
    links: [],
    metrics: [],
    assets: [
      {
        kind: "diagram",
        path: "/media/projects/cisco-agentic-runbook-creator/system-placeholder.svg",
        alt: "Placeholder for the approved Cisco runbook system diagram",
        caption: "Architecture artwork will be replaced during final content work.",
        width: 1200,
        height: 675,
        placeholder: true,
      },
    ],
  },
  {
    slug: "repoframe",
    title: "RepoFrame",
    category: "Developer Tools",
    shortDescription:
      "A repository-analysis tool that combines deterministic inspection with bounded evidence retrieval to build grounded project profiles for resumes, portfolios, documentation, and interviews.",
    role: "Creator and full-stack engineer",
    startDate: null,
    endDate: null,
    technologies: ["Next.js", "TypeScript", "FastAPI", "Python", "GitHub API"],
    accent: "purple",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 20,
    displayInMap: true,
    presentation: "case-study",
    priority: "featured",
    caseStudyKey: "repoframe",
    links: [],
    metrics: [
      {
        label: "Evidence policy",
        value: "Bounded",
        context: "Retrieval is limited to allowlisted repository evidence.",
        sourceNote: "Confirm wording against the shipped implementation before release.",
      },
      {
        label: "Primary modes",
        value: "4",
        context: "Resume, portfolio, README, and interview-oriented outputs.",
        sourceNote: "Verify the final public feature inventory before release.",
      },
    ],
    assets: [
      {
        kind: "diagram",
        path: "/media/projects/repoframe/architecture-placeholder.svg",
        alt: "Placeholder for the RepoFrame repository-analysis architecture",
        width: 1200,
        height: 675,
        placeholder: true,
      },
      {
        kind: "screenshot",
        path: "/media/projects/repoframe/profile-placeholder.svg",
        alt: "Placeholder for a RepoFrame evidence-backed project profile",
        width: 1200,
        height: 675,
        placeholder: true,
      },
      {
        kind: "screenshot",
        path: "/media/projects/repoframe/audit-placeholder.svg",
        alt: "Placeholder for the RepoFrame agentic audit interface",
        width: 1200,
        height: 675,
        placeholder: true,
      },
    ],
  },
  {
    slug: "nucurrent-inventory-system",
    title: "NuCurrent Inventory System",
    category: "Full-stack Software",
    shortDescription:
      "A React, FastAPI, and SQL inventory platform built through CUBE Consulting at UIUC to make operational inventory data easier to maintain and use.",
    role: "Full-stack developer",
    startDate: null,
    endDate: null,
    technologies: ["React", "FastAPI", "SQL"],
    accent: "green",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 30,
    displayInMap: true,
    presentation: "case-study",
    priority: "supporting",
    caseStudyKey: "nucurrent-inventory-system",
    links: [],
    metrics: [],
    assets: [],
  },
  {
    slug: "smartlift-sleeve",
    title: "SmartLift Sleeve",
    category: "Hardware",
    shortDescription:
      "A wearable lifting prototype combining sensors, custom PCB work, rep counting, exertion zones, and immediate LED feedback in a physical training system.",
    role: "Hardware and embedded systems engineer",
    startDate: null,
    endDate: null,
    technologies: ["Embedded C", "PCB Design", "Sensors", "Digital Logic"],
    accent: "purple",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 40,
    displayInMap: true,
    presentation: "case-study",
    priority: "supporting",
    caseStudyKey: "smartlift-sleeve",
    links: [],
    metrics: [],
    assets: [
      {
        kind: "hardware-photo",
        path: "/media/projects/smartlift-sleeve/hardware-placeholder.svg",
        alt: "Placeholder for a SmartLift Sleeve hardware photograph",
        width: 1200,
        height: 675,
        placeholder: true,
      },
    ],
  },
  {
    slug: "quackta",
    title: "QuackTA",
    category: "Embedded Systems",
    shortDescription:
      "A physical study companion built with Raspberry Pi, Arduino, a custom duck enclosure, guided AI tutoring behavior, an app interface, and scheduling support.",
    role: "Embedded and application developer",
    startDate: null,
    endDate: null,
    technologies: ["Raspberry Pi", "Arduino", "Python", "3D Printing", "GPT-4o Mini"],
    accent: "mixed",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 50,
    displayInMap: true,
    presentation: "case-study",
    priority: "supporting",
    caseStudyKey: "quackta",
    links: [],
    metrics: [],
    assets: [],
  },
  {
    slug: "lucky-arduino",
    title: "Lucky Arduino",
    category: "Embedded Systems",
    shortDescription:
      "An early Arduino project that will appear as a substantial archive card while its strongest technical details and supporting media are assembled.",
    role: "Builder",
    startDate: null,
    endDate: null,
    technologies: ["Arduino", "Embedded C"],
    accent: "green",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 100,
    displayInMap: false,
    presentation: "archive-card",
    priority: "archive",
    caseStudyKey: null,
    links: [],
    metrics: [],
    assets: [],
  },
  {
    slug: "backbuddy",
    title: "BackBuddy",
    category: "Hardware",
    shortDescription:
      "An older physical-system project reserved for a public archive card until its problem framing, personal contribution, and evidence receive a final content pass.",
    role: "Builder",
    startDate: null,
    endDate: null,
    technologies: ["Hardware Prototyping"],
    accent: "purple",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 110,
    displayInMap: false,
    presentation: "archive-card",
    priority: "archive",
    caseStudyKey: null,
    links: [],
    metrics: [],
    assets: [],
  },
  {
    slug: "neurify",
    title: "Neurify",
    category: "AI Systems",
    shortDescription:
      "An earlier AI-focused project that will launch as an archive card after its technical scope and public evidence are verified.",
    role: "Developer",
    startDate: null,
    endDate: null,
    technologies: ["Machine Learning"],
    accent: "mixed",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 120,
    displayInMap: false,
    presentation: "archive-card",
    priority: "archive",
    caseStudyKey: null,
    links: [],
    metrics: [],
    assets: [],
  },
  {
    slug: "agrisense",
    title: "AgriSense",
    category: "Embedded Systems",
    shortDescription:
      "An earlier sensing project planned as a concise public archive entry while final implementation details and media are collected.",
    role: "Developer",
    startDate: null,
    endDate: null,
    technologies: ["Sensors", "Embedded Systems"],
    accent: "green",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 130,
    displayInMap: false,
    presentation: "archive-card",
    priority: "archive",
    caseStudyKey: null,
    links: [],
    metrics: [],
    assets: [],
  },
  {
    slug: "risenrun-wifi-alarm-clock",
    title: "COSMOS RiseNRun Wi-Fi Alarm Clock",
    category: "Embedded Systems",
    shortDescription:
      "A Wi-Fi alarm-clock project from the COSMOS program that will launch as an archive card highlighting the physical build and connected-system lessons.",
    role: "Developer",
    startDate: null,
    endDate: null,
    technologies: ["Wi-Fi", "Embedded Systems", "Hardware Prototyping"],
    accent: "purple",
    publication: "draft",
    contentStatus: "placeholder",
    launchTarget: "initial",
    displayOrder: 140,
    displayInMap: false,
    presentation: "archive-card",
    priority: "archive",
    caseStudyKey: null,
    links: [],
    metrics: [],
    assets: [],
  },
] as const satisfies readonly Project[];

